const gulp = require('gulp')
const concat = require('gulp-concat')
const gfi = require("gulp-file-insert")
gulp.src('app/**/*.js')
    .pipe(concat('renderer.js'))
    .pipe(gulp.dest(''))
gulp.src('app/Home/HomeView.html')
  .pipe(gfi({'<!--gulp:insert(STORICO)-->': 'app/Storico/storicoView.html'}))
  .pipe(concat('app.html'))
  .pipe(gulp.dest('app/Home/'))