-- MySQL Script generated by MySQL Workbench
-- mer 28 mar 2018 09:56:12 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gestione_emergenze
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gestione_emergenze
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestione_emergenze` DEFAULT CHARACTER SET utf8 ;
USE `gestione_emergenze` ;

-- -----------------------------------------------------
-- Table `gestione_emergenze`.`emergenza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestione_emergenze`.`emergenza` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `data` DATETIME NOT NULL,
  `chiusura` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestione_emergenze`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestione_emergenze`.`tipo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `elencabile` BIT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 0;


-- -----------------------------------------------------
-- Table `gestione_emergenze`.`intervento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestione_emergenze`.`intervento` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `indirizzo` VARCHAR(100) NOT NULL,
  `contatto` VARCHAR(100) NOT NULL,
  `altro` VARCHAR(45) NULL,
  `seg` DATETIME NOT NULL,
  `inizio` DATETIME NULL,
  `fine` DATETIME NULL,
  `x` DECIMAL(30,25) NOT NULL,
  `y` DECIMAL(30,25) NOT NULL,
  `tipo_id` INT UNSIGNED NOT NULL,
  `emergenza_id` INT UNSIGNED NOT NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`id`, `emergenza_id`),
  INDEX `fk_intervento_tipo1_idx` (`tipo_id` ASC),
  INDEX `fk_intervento_emergenza1_idx` (`emergenza_id` ASC),
  CONSTRAINT `fk_intervento_tipo1`
    FOREIGN KEY (`tipo_id`)
    REFERENCES `gestione_emergenze`.`tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_intervento_emergenza1`
    FOREIGN KEY (`emergenza_id`)
    REFERENCES `gestione_emergenze`.`emergenza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestione_emergenze`.`mezzo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestione_emergenze`.`mezzo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `elencabile` BIT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 0;


-- -----------------------------------------------------
-- Table `gestione_emergenze`.`volontario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestione_emergenze`.`volontario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `elencabile` BIT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestione_emergenze`.`attrezzatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestione_emergenze`.`attrezzatura` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `elencabile` BIT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestione_emergenze`.`isVolontario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestione_emergenze`.`isVolontario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `intervento_id` INT UNSIGNED NOT NULL,
  `volontario_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `intervento_id`, `volontario_id`),
  INDEX `fk_isVolontario_volontario_id` (`volontario_id` ASC),
  INDEX `fk_isVolonatrio_intervento_id` (`intervento_id` ASC),
  CONSTRAINT `fk_isVolontario_intervento`
    FOREIGN KEY (`intervento_id`)
    REFERENCES `gestione_emergenze`.`intervento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_isVolontario_volontario`
    FOREIGN KEY (`volontario_id`)
    REFERENCES `gestione_emergenze`.`volontario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestione_emergenze`.`isAttrezzatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestione_emergenze`.`isAttrezzatura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `intervento_id` INT UNSIGNED NOT NULL,
  `attrezzatura_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `intervento_id`, `attrezzatura_id`),
  INDEX `fk_isAtrezzatura_intervento_id` (`intervento_id` ASC),
  INDEX `fk_isAttrezzatura_attrezzatura_id` (`attrezzatura_id` ASC),
  CONSTRAINT `fk_isAttrezzatura_attrezzatura`
    FOREIGN KEY (`attrezzatura_id`)
    REFERENCES `gestione_emergenze`.`attrezzatura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_isAttrezzatura_intervento`
    FOREIGN KEY (`intervento_id`)
    REFERENCES `gestione_emergenze`.`intervento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestione_emergenze`.`isMezzo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestione_emergenze`.`isMezzo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `intervento_id` INT UNSIGNED NOT NULL,
  `mezzo_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `intervento_id`, `mezzo_id`),
  INDEX `fk_isMezzo_mezzo_id` (`mezzo_id` ASC),
  INDEX `fk_isMezzo_intervento_id` (`intervento_id` ASC),
  CONSTRAINT `fk_isMezzo_intervento`
    FOREIGN KEY (`intervento_id`)
    REFERENCES `gestione_emergenze`.`intervento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_isMezzo_mezzo`
    FOREIGN KEY (`mezzo_id`)
    REFERENCES `gestione_emergenze`.`mezzo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `gestione_emergenze`.`tipo`
-- -----------------------------------------------------
START TRANSACTION;
USE `gestione_emergenze`;
INSERT INTO `gestione_emergenze`.`tipo` (`id`, `nome`, `elencabile`) VALUES (0, 'Altro', 0);

COMMIT;

